package mod.upcraftlp.spookycraft;

import static mod.upcraftlp.spookycraft.Reference.CREDITS;
import static mod.upcraftlp.spookycraft.Reference.DEPENDENCIES;
import static mod.upcraftlp.spookycraft.Reference.MCVERSIONS;
import static mod.upcraftlp.spookycraft.Reference.MODID;
import static mod.upcraftlp.spookycraft.Reference.MODNAME;
import static mod.upcraftlp.spookycraft.Reference.MOD_DESCRIPTION;
import static mod.upcraftlp.spookycraft.Reference.UPDATE_JSON;
import static mod.upcraftlp.spookycraft.Reference.VERSION;
import static mod.upcraftlp.spookycraft.Reference.WEBSITE;
import static mod.upcraftlp.spookycraft.Reference.authors;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import mod.upcraftlp.spookycraft.init.SpookyTabs;
import mod.upcraftlp.spookycraft.proxy.Proxy;
import net.minecraft.init.Blocks;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;

@Mod(
        certificateFingerprint = Reference.FINGERPRINT_KEY,
        name = MODNAME,
        version = VERSION,
        acceptedMinecraftVersions = MCVERSIONS,
        modid = MODID,
        dependencies = DEPENDENCIES,
        updateJSON = UPDATE_JSON
)
public class Main {

    @Mod.Instance(MODID)
    public static Main INSTACE;

    @SidedProxy(clientSide = Reference.CLIENTPROXY, serverSide = Reference.SERVERPROXY)
    public static Proxy proxy;

    private static final Logger log = LogManager.getLogger(MODID);

    public static Logger getLogger() {
        return log;
    }

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {

        //TODO funny quotes for halloween!

        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.authorList = authors;
        data.credits = CREDITS;
        data.description = MOD_DESCRIPTION;
        data.url = WEBSITE;
        proxy.preInit(event);
        SpookyTabs.SPOOKY_TAB.setIconStack(new ItemStack(Blocks.LIT_PUMPKIN)); //TODO different icon?
        log.info("Pre-Initialization finished.");
    }

    @Mod.EventHandler
    public void init(FMLInitializationEvent event) {
        proxy.init(event);
        log.info("Initialization finished.");
    }

    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event) {
        proxy.postInit(event);
        log.info("Post-Initialization finished.");
    }

    @Mod.EventHandler
    public void onServerStarting(FMLServerStartingEvent event) {
        proxy.serverStarting(event);
        log.info("Taking over the world!");
    }

}
